name: Publish Gem Release

on:
  push:
    tags:
      - v*

jobs:
  publish-release:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - uses: planningcenter/gh-action-publish-internal-gem@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
